table CatFacts
	lineageTag: 8f1e2d3c-4b5a-6978-90ab-cdef12340001

	measure 'Nombre de faits' = COUNTROWS(CatFacts)
		formatString: 0
		lineageTag: 8f1e2d3c-4b5a-6978-90ab-cdef12340002

	measure 'Longueur (car.)' = SUM(CatFacts[Length])
		formatString: 0
		lineageTag: 8f1e2d3c-4b5a-6978-90ab-cdef12340003

	column FactIndex
		dataType: int64
		formatString: 0
		lineageTag: 8f1e2d3c-4b5a-6978-90ab-cdef12340101
		summarizeBy: none
		sourceColumn: FactIndex

		annotation SummarizationSetBy = Automatic

	column FactText
		dataType: string
		lineageTag: 8f1e2d3c-4b5a-6978-90ab-cdef12340102
		summarizeBy: none
		sourceColumn: FactText

		annotation SummarizationSetBy = Automatic

	column Length
		dataType: int64
		formatString: 0
		lineageTag: 8f1e2d3c-4b5a-6978-90ab-cdef12340103
		summarizeBy: sum
		sourceColumn: Length

		annotation SummarizationSetBy = Automatic

	partition CatFacts = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://catfact.ninja/facts?limit=15")),
				    data = Source[data],
				    tbl = Table.FromRecords(data),
				    Renamed = Table.RenameColumns(tbl, {{"fact", "FactText"}, {"length", "Length"}}),
				    #"Types" = Table.TransformColumnTypes(Renamed, {{"FactText", type text}, {"Length", Int64.Type}}),
				    WithIndex = Table.AddIndexColumn(#"Types", "FactIndex", 1, 1, Int64.Type)
				in
				    WithIndex

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

