table Dim_Route
	lineageTag: 7a5ae841-1851-412e-9106-6f0ebafaadca

	column RouteID
		dataType: string
		lineageTag: 47a93ad5-25d1-433a-9de0-2544f71ef542
		summarizeBy: none
		sourceColumn: RouteID

		annotation SummarizationSetBy = Automatic

	column Origin
		dataType: string
		lineageTag: 3a5cd032-6e02-4987-a0de-6cb8947d9461
		summarizeBy: none
		sourceColumn: Origin

		annotation SummarizationSetBy = Automatic

	column Destination
		dataType: string
		lineageTag: bafee8b6-6d7b-4818-8486-9e59d92649c0
		summarizeBy: none
		sourceColumn: Destination

		annotation SummarizationSetBy = Automatic

	column HaulType
		dataType: string
		lineageTag: 6d5a744c-d08e-486a-984f-eb7bd9eff634
		summarizeBy: none
		sourceColumn: HaulType

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: edfc779b-8fd1-440a-948f-c92b098c5ff0
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: c57e4cca-bbfb-4bbb-89b4-3b4bdfd2b004
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column DistanceKm
		dataType: int64
		formatString: 0
		lineageTag: ec188000-4d88-43c3-981f-92e44ed10ac0
		summarizeBy: sum
		sourceColumn: DistanceKm

		annotation SummarizationSetBy = Automatic

	partition Dim_Route = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fbazin\Downloads\base_mockup_trafic_passager_aeroport_powerbi.xlsx"), null, true),
				    Dim_Route_Sheet = Source{[Item="Dim_Route",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Dim_Route_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"RouteID", type text}, {"Origin", type text}, {"Destination", type text}, {"HaulType", type text}, {"Market", type text}, {"Region", type text}, {"DistanceKm", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

