table DimCheckpoint
	lineageTag: 2703fe60-4c6e-418f-aead-fbfb63260e36

	column CheckpointID
		dataType: string
		lineageTag: e92cd7e3-b3b6-4b6e-96e9-5748861c295e
		summarizeBy: none
		sourceColumn: CheckpointID

		annotation SummarizationSetBy = Automatic

	column TerminalID
		dataType: string
		lineageTag: 7feb443d-28cb-47ec-96e5-778c9c61e240
		summarizeBy: none
		sourceColumn: TerminalID

		annotation SummarizationSetBy = Automatic

	column ProcessArea
		dataType: string
		lineageTag: 68489d44-3f06-4893-989c-c789a6119a25
		summarizeBy: none
		sourceColumn: ProcessArea

		annotation SummarizationSetBy = Automatic

	column NominalCapacityPaxPerHour
		dataType: int64
		formatString: 0
		lineageTag: 3f9bbf90-467f-4b15-bb79-a88dc4b95eb9
		summarizeBy: sum
		sourceColumn: NominalCapacityPaxPerHour

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 28476fd2-1c26-4c12-88c1-84656592ce71
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	partition DimCheckpoint = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fbazin\Downloads\base_mockup_trafic_passager_aeroport_powerbi.xlsx"), null, true),
				    DimCheckpoint_Table = Source{[Item="DimCheckpoint",Kind="Table"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(DimCheckpoint_Table,{{"CheckpointID", type text}, {"TerminalID", type text}, {"ProcessArea", type text}, {"NominalCapacityPaxPerHour", Int64.Type}, {"Criticality", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

