table DimDate
	lineageTag: cc2bafc5-59ae-41a6-b44e-a1560711278b

	column Date
		dataType: int64
		formatString: 0
		lineageTag: 0bc9e481-a7df-4a23-b192-f0d43099ffb7
		summarizeBy: sum
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 48bab504-8a1e-4104-97d3-1b466c2c778c
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: 0
		lineageTag: 7162993d-ab92-4300-8d1b-e7dc5bca3b1f
		summarizeBy: sum
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 18a4e371-1d50-4f86-a2e4-6a03a1c73de8
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column ISOWeek
		dataType: int64
		formatString: 0
		lineageTag: 7dae9b69-4ef7-47ff-bfb1-43294f17763b
		summarizeBy: sum
		sourceColumn: ISOWeek

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 55c9d5fd-2353-4733-b114-0d3b8c39aa31
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f7268fbf-8360-4e03-b2a4-0235905ef189
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: int64
		formatString: 0
		lineageTag: 0110c280-1e17-4b74-888e-9d21d69ed2f8
		summarizeBy: sum
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column Seasonality
		dataType: string
		lineageTag: d258a1e2-a530-493f-8ed5-75730e67e891
		summarizeBy: none
		sourceColumn: Seasonality

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fbazin\Downloads\base_mockup_trafic_passager_aeroport_powerbi.xlsx"), null, true),
				    DimDate_Table = Source{[Item="DimDate",Kind="Table"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(DimDate_Table,{{"Date", Int64.Type}, {"Year", Int64.Type}, {"MonthNo", Int64.Type}, {"MonthName", type text}, {"ISOWeek", Int64.Type}, {"Day", Int64.Type}, {"DayName", type text}, {"IsWeekend", Int64.Type}, {"Seasonality", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

