table DimResource
	lineageTag: d0430ea4-7357-4440-8a94-054e26fe4c19

	column ResourcePoolID
		dataType: string
		lineageTag: b0e5886c-77c8-492f-8fea-cfc1226fbe3f
		summarizeBy: none
		sourceColumn: ResourcePoolID

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		lineageTag: 42b87145-7e4a-49ca-8a51-e4217417905c
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: a570cc63-f463-4cf7-8fd7-1ac222dc6160
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column PlannedHeadcount
		dataType: int64
		formatString: 0
		lineageTag: 7e362bd0-ebaa-424c-9929-c6b0312270db
		summarizeBy: sum
		sourceColumn: PlannedHeadcount

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 043a8dde-e3a3-4528-8893-f544a232d14e
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	partition DimResource = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fbazin\Downloads\base_mockup_trafic_passager_aeroport_powerbi.xlsx"), null, true),
				    DimResource_Table = Source{[Item="DimResource",Kind="Table"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(DimResource_Table,{{"ResourcePoolID", type text}, {"Role", type text}, {"Shift", type text}, {"PlannedHeadcount", Int64.Type}, {"Department", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

