table Fact_PaxFlow_Hourly
	lineageTag: deeecef8-e522-4340-9a69-2c0e8000cace

	column Date
		dataType: int64
		formatString: 0
		lineageTag: c94cd895-ab28-41e4-9bbe-8e20d953eef5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: 900625b3-0da7-469a-94c4-edc38487405f
		summarizeBy: sum
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column TerminalID
		dataType: string
		lineageTag: 06b71dd0-b49d-4c10-a2f4-bf89558fa0bb
		summarizeBy: none
		sourceColumn: TerminalID

		annotation SummarizationSetBy = Automatic

	column DepartingPax
		dataType: int64
		formatString: 0
		lineageTag: 929574c0-3a1a-4f22-bd71-cba4811bedb7
		summarizeBy: sum
		sourceColumn: DepartingPax

		annotation SummarizationSetBy = Automatic

	column ArrivingPax
		dataType: int64
		formatString: 0
		lineageTag: 26c6bff8-3bd2-460d-b295-4adff33d9ba8
		summarizeBy: sum
		sourceColumn: ArrivingPax

		annotation SummarizationSetBy = Automatic

	column TransferPax
		dataType: int64
		formatString: 0
		lineageTag: d0b8f49a-9788-4d83-99f5-f53e099caf47
		summarizeBy: sum
		sourceColumn: TransferPax

		annotation SummarizationSetBy = Automatic

	column TotalPax
		dataType: int64
		formatString: 0
		lineageTag: eb33519d-4596-4a17-844b-34d930185c2f
		summarizeBy: sum
		sourceColumn: TotalPax

		annotation SummarizationSetBy = Automatic

	partition Fact_PaxFlow_Hourly = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fbazin\Downloads\base_mockup_trafic_passager_aeroport_powerbi.xlsx"), null, true),
				    Fact_PaxFlow_Hourly_Sheet = Source{[Item="Fact_PaxFlow_Hourly",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Fact_PaxFlow_Hourly_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Date", Int64.Type}, {"Hour", Int64.Type}, {"TerminalID", type text}, {"DepartingPax", Int64.Type}, {"ArrivingPax", Int64.Type}, {"TransferPax", Int64.Type}, {"TotalPax", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

