table Fact_Flights
	lineageTag: 558127e2-f5aa-4834-a37b-e31029e1baf8

	measure 'Total passagers' =
			SUM(Fact_Flights[PassengerCount])
		formatString: 0
		lineageTag: 221e1849-d0b8-4c4f-83dc-6c2f2f8f5f01

	measure 'Capacite sieges' =
			SUM(Fact_Flights[SeatCapacity])
		formatString: 0
		lineageTag: 42ae998d-5c8e-4c3e-b5d5-a3ef7fc14d65

	measure 'Nombre de vols' =
			COUNTROWS(Fact_Flights)
		formatString: 0
		lineageTag: 1230ac4b-61d4-478c-b565-b1979d73a002

	measure 'Retard moyen (min)' =
			AVERAGE(Fact_Flights[DelayMinutes])
		formatString: 0.0
		lineageTag: e8f72582-4083-47a9-b26c-cd7577387d82

	measure 'Taux de remplissage' =
			DIVIDE([Total passagers], [Capacite sieges])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8320de46-889f-469e-9e71-9a3491e4fd9c

	measure 'Vols retardes' =
			CALCULATE([Nombre de vols], Fact_Flights[DelayMinutes] > 15)
		formatString: 0
		lineageTag: 6e2729a5-fb18-48bf-9c40-ecf8178cb8f8

	measure 'Taux vols retardes' =
			DIVIDE([Vols retardes], [Nombre de vols])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8a664de7-12f8-4fd5-a4df-b5bdbe63c326

	measure 'Flux passagers horaire' =
			SUM(Fact_PaxFlow_Hourly[TotalPax])
		formatString: 0
		lineageTag: 9b0b3149-a7b0-48d5-ad5f-91f9bf0a1e01

	measure Incidents =
			COUNTROWS(Fact_Incidents)
		formatString: 0
		lineageTag: 9e5b8b60-687c-4a2c-a8fb-164430a944d0

	measure 'Passagers impactes' =
			SUM(Fact_Incidents[PassengerImpacted])
		formatString: 0
		lineageTag: e2871474-1687-4b87-8b65-ae1a6b07e52a

	measure 'Attente moyenne (min)' =
			AVERAGE(Fact_QueueEvents[AvgWaitMin])
		formatString: 0.0
		lineageTag: b2da7e4d-68cc-4044-880e-2e8b2a98936b

	measure 'Bagages charges' =
			SUM(Fact_Baggage[LoadedBags])
		formatString: 0
		lineageTag: db8b51dc-c650-4c37-98cd-3c096f408050

	measure 'Bagages mal traites' =
			SUM(Fact_Baggage[MishandledBags])
		formatString: 0
		lineageTag: d1eda74b-e68b-4e44-b942-7ea5b035fc1f

	measure 'Taux bagages mal traites' =
			DIVIDE([Bagages mal traites], [Bagages charges])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3f6fcda0-3806-45f7-9f77-713fcf905312

	measure 'Signal total passagers' =
			VAR CurrentValue = [Total passagers]
			VAR PreviousValue =
				CALCULATE([Total passagers], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta >= 0,
						"Vert - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%"),
						"Rouge - baisse vs periode precedente: " & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000001

	measure 'Signal nombre de vols' =
			VAR CurrentValue = [Nombre de vols]
			VAR PreviousValue =
				CALCULATE([Nombre de vols], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta >= 0,
						"Vert - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%"),
						"Rouge - baisse vs periode precedente: " & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000002

	measure 'Signal capacite sieges' =
			VAR CurrentValue = [Capacite sieges]
			VAR PreviousValue =
				CALCULATE([Capacite sieges], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta >= 0,
						"Vert - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%"),
						"Rouge - baisse vs periode precedente: " & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000003

	measure 'Signal taux de remplissage' =
			VAR CurrentValue = [Taux de remplissage]
			VAR PreviousValue =
				CALCULATE([Taux de remplissage], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta >= 0,
						"Vert - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%"),
						"Rouge - baisse vs periode precedente: " & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000004

	measure 'Signal flux passagers horaire' =
			VAR CurrentValue = [Flux passagers horaire]
			VAR PreviousValue =
				CALCULATE([Flux passagers horaire], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta >= 0,
						"Vert - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%"),
						"Rouge - baisse vs periode precedente: " & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000005

	measure 'Signal retard moyen' =
			VAR CurrentValue = [Retard moyen (min)]
			VAR PreviousValue =
				CALCULATE([Retard moyen (min)], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta <= 0,
						"Vert - baisse vs periode precedente: " & FORMAT(Delta, "0.0%"),
						"Rouge - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000006

	measure 'Signal vols retardes' =
			VAR CurrentValue = [Vols retardes]
			VAR PreviousValue =
				CALCULATE([Vols retardes], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta <= 0,
						"Vert - baisse vs periode precedente: " & FORMAT(Delta, "0.0%"),
						"Rouge - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000007

	measure 'Signal taux vols retardes' =
			VAR CurrentValue = [Taux vols retardes]
			VAR PreviousValue =
				CALCULATE([Taux vols retardes], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta <= 0,
						"Vert - baisse vs periode precedente: " & FORMAT(Delta, "0.0%"),
						"Rouge - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000008

	measure 'Signal incidents' =
			VAR CurrentValue = [Incidents]
			VAR PreviousValue =
				CALCULATE([Incidents], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta <= 0,
						"Vert - baisse vs periode precedente: " & FORMAT(Delta, "0.0%"),
						"Rouge - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000009

	measure 'Signal passagers impactes' =
			VAR CurrentValue = [Passagers impactes]
			VAR PreviousValue =
				CALCULATE([Passagers impactes], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta <= 0,
						"Vert - baisse vs periode precedente: " & FORMAT(Delta, "0.0%"),
						"Rouge - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000010

	measure 'Signal attente moyenne' =
			VAR CurrentValue = [Attente moyenne (min)]
			VAR PreviousValue =
				CALCULATE([Attente moyenne (min)], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta <= 0,
						"Vert - baisse vs periode precedente: " & FORMAT(Delta, "0.0%"),
						"Rouge - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000011

	measure 'Signal taux bagages mal traites' =
			VAR CurrentValue = [Taux bagages mal traites]
			VAR PreviousValue =
				CALCULATE([Taux bagages mal traites], DATEADD('Dim_Date'[Date], -1, MONTH))
			VAR Delta = DIVIDE(CurrentValue - PreviousValue, PreviousValue)
			RETURN
				IF(
					ISBLANK(PreviousValue),
					"Tendance non disponible",
					IF(
						Delta <= 0,
						"Vert - baisse vs periode precedente: " & FORMAT(Delta, "0.0%"),
						"Rouge - hausse vs periode precedente: +" & FORMAT(Delta, "0.0%")
					)
				)
		lineageTag: 41000000-0000-0000-0000-000000000012

	column FlightID
		dataType: string
		lineageTag: 69fb4484-187d-45ae-b035-f72a6670e46d
		summarizeBy: none
		sourceColumn: FlightID

		annotation SummarizationSetBy = Automatic

	column FlightDate
		dataType: int64
		formatString: 0
		lineageTag: 77bc851f-ec6a-462c-940c-0b3c1c110a97
		summarizeBy: none
		sourceColumn: FlightDate

		annotation SummarizationSetBy = Automatic

	column ScheduledDateTime
		dataType: double
		lineageTag: aff687f8-9660-4622-adc5-3757a4ae54b4
		summarizeBy: sum
		sourceColumn: ScheduledDateTime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ActualDateTime
		dataType: double
		lineageTag: 181623fe-6f14-4b3c-b364-1ed48a233558
		summarizeBy: sum
		sourceColumn: ActualDateTime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MovementType
		dataType: string
		lineageTag: b5f042d1-1c15-45e6-86c6-f4ba41dcffb6
		summarizeBy: none
		sourceColumn: MovementType

		annotation SummarizationSetBy = Automatic

	column AirlineID
		dataType: string
		lineageTag: 1eaddbd9-bd00-469c-89ee-2613dc352700
		summarizeBy: none
		sourceColumn: AirlineID

		annotation SummarizationSetBy = Automatic

	column RouteID
		dataType: string
		lineageTag: 548e359e-e346-43e3-b0d6-7bdaf107110d
		summarizeBy: none
		sourceColumn: RouteID

		annotation SummarizationSetBy = Automatic

	column TerminalID
		dataType: string
		lineageTag: d38765a2-012c-41e2-a9e5-35c28aa9498a
		summarizeBy: none
		sourceColumn: TerminalID

		annotation SummarizationSetBy = Automatic

	column AircraftType
		dataType: string
		lineageTag: e734e8ad-71de-48ae-86f9-833640dac6f7
		summarizeBy: none
		sourceColumn: AircraftType

		annotation SummarizationSetBy = Automatic

	column SeatCapacity
		dataType: int64
		formatString: 0
		lineageTag: 7e8467a2-3141-4ecf-9358-55a6913396eb
		summarizeBy: sum
		sourceColumn: SeatCapacity

		annotation SummarizationSetBy = Automatic

	column PassengerCount
		dataType: int64
		formatString: 0
		lineageTag: 868482cc-f744-4df7-9f31-aa5275e9682b
		summarizeBy: sum
		sourceColumn: PassengerCount

		annotation SummarizationSetBy = Automatic

	column FlightStatus
		dataType: string
		lineageTag: 85b402a4-ff34-486e-b451-cbf7c334ef2a
		summarizeBy: none
		sourceColumn: FlightStatus

		annotation SummarizationSetBy = Automatic

	column DelayMinutes
		dataType: int64
		formatString: 0
		lineageTag: b5652d5b-7d52-40f1-bb50-5afa37ea43b3
		summarizeBy: sum
		sourceColumn: DelayMinutes

		annotation SummarizationSetBy = Automatic

	column Gate
		dataType: int64
		formatString: 0
		lineageTag: 2d87c6fb-c2d8-4df0-8507-f38ad491cd0d
		summarizeBy: sum
		sourceColumn: Gate

		annotation SummarizationSetBy = Automatic

	column BaggageBelt
		dataType: string
		lineageTag: 743a784d-cfc9-4f60-8e0b-6dfa7b5a4447
		summarizeBy: none
		sourceColumn: BaggageBelt

		annotation SummarizationSetBy = Automatic

	partition Fact_Flights = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fbazin\Downloads\base_mockup_trafic_passager_aeroport_powerbi.xlsx"), null, true),
				    Fact_Flights_Sheet = Source{[Item="Fact_Flights",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Fact_Flights_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"FlightID", type text}, {"FlightDate", Int64.Type}, {"ScheduledDateTime", type number}, {"ActualDateTime", type number}, {"MovementType", type text}, {"AirlineID", type text}, {"RouteID", type text}, {"TerminalID", type text}, {"AircraftType", type text}, {"SeatCapacity", Int64.Type}, {"PassengerCount", Int64.Type}, {"FlightStatus", type text}, {"DelayMinutes", Int64.Type}, {"Gate", Int64.Type}, {"BaggageBelt", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

