table Fact_Flights
	lineageTag: 558127e2-f5aa-4834-a37b-e31029e1baf8

	column FlightID
		dataType: string
		lineageTag: 69fb4484-187d-45ae-b035-f72a6670e46d
		summarizeBy: none
		sourceColumn: FlightID

		annotation SummarizationSetBy = Automatic

	column FlightDate
		dataType: int64
		formatString: 0
		lineageTag: 77bc851f-ec6a-462c-940c-0b3c1c110a97
		summarizeBy: none
		sourceColumn: FlightDate

		annotation SummarizationSetBy = Automatic

	column ScheduledDateTime
		dataType: double
		lineageTag: aff687f8-9660-4622-adc5-3757a4ae54b4
		summarizeBy: sum
		sourceColumn: ScheduledDateTime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ActualDateTime
		dataType: double
		lineageTag: 181623fe-6f14-4b3c-b364-1ed48a233558
		summarizeBy: sum
		sourceColumn: ActualDateTime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MovementType
		dataType: string
		lineageTag: b5f042d1-1c15-45e6-86c6-f4ba41dcffb6
		summarizeBy: none
		sourceColumn: MovementType

		annotation SummarizationSetBy = Automatic

	column AirlineID
		dataType: string
		lineageTag: 1eaddbd9-bd00-469c-89ee-2613dc352700
		summarizeBy: none
		sourceColumn: AirlineID

		annotation SummarizationSetBy = Automatic

	column RouteID
		dataType: string
		lineageTag: 548e359e-e346-43e3-b0d6-7bdaf107110d
		summarizeBy: none
		sourceColumn: RouteID

		annotation SummarizationSetBy = Automatic

	column TerminalID
		dataType: string
		lineageTag: d38765a2-012c-41e2-a9e5-35c28aa9498a
		summarizeBy: none
		sourceColumn: TerminalID

		annotation SummarizationSetBy = Automatic

	column AircraftType
		dataType: string
		lineageTag: e734e8ad-71de-48ae-86f9-833640dac6f7
		summarizeBy: none
		sourceColumn: AircraftType

		annotation SummarizationSetBy = Automatic

	column SeatCapacity
		dataType: int64
		formatString: 0
		lineageTag: 7e8467a2-3141-4ecf-9358-55a6913396eb
		summarizeBy: sum
		sourceColumn: SeatCapacity

		annotation SummarizationSetBy = Automatic

	column PassengerCount
		dataType: int64
		formatString: 0
		lineageTag: 868482cc-f744-4df7-9f31-aa5275e9682b
		summarizeBy: sum
		sourceColumn: PassengerCount

		annotation SummarizationSetBy = Automatic

	column FlightStatus
		dataType: string
		lineageTag: 85b402a4-ff34-486e-b451-cbf7c334ef2a
		summarizeBy: none
		sourceColumn: FlightStatus

		annotation SummarizationSetBy = Automatic

	column DelayMinutes
		dataType: int64
		formatString: 0
		lineageTag: b5652d5b-7d52-40f1-bb50-5afa37ea43b3
		summarizeBy: sum
		sourceColumn: DelayMinutes

		annotation SummarizationSetBy = Automatic

	column Gate
		dataType: int64
		formatString: 0
		lineageTag: 2d87c6fb-c2d8-4df0-8507-f38ad491cd0d
		summarizeBy: sum
		sourceColumn: Gate

		annotation SummarizationSetBy = Automatic

	column BaggageBelt
		dataType: string
		lineageTag: 743a784d-cfc9-4f60-8e0b-6dfa7b5a4447
		summarizeBy: none
		sourceColumn: BaggageBelt

		annotation SummarizationSetBy = Automatic

	partition Fact_Flights = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fbazin\Downloads\base_mockup_trafic_passager_aeroport_powerbi.xlsx"), null, true),
				    Fact_Flights_Sheet = Source{[Item="Fact_Flights",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Fact_Flights_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"FlightID", type text}, {"FlightDate", Int64.Type}, {"ScheduledDateTime", type number}, {"ActualDateTime", type number}, {"MovementType", type text}, {"AirlineID", type text}, {"RouteID", type text}, {"TerminalID", type text}, {"AircraftType", type text}, {"SeatCapacity", Int64.Type}, {"PassengerCount", Int64.Type}, {"FlightStatus", type text}, {"DelayMinutes", Int64.Type}, {"Gate", Int64.Type}, {"BaggageBelt", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

